### ISSUE TITLE
Compiling Theli on macOS Catalina

### ISSUE THREAD

**Issue by svdwal** [schirmermischa/THELI#3]
I have managed to compile Theli on macOS Catalina. There were some issues preventing compilation, for which I have fixes

1) Apple clang does not recognise the -fopenmp.
The solution is to prepend the -Xpreprocessor switch before -fopenmp, and add -lomp to the link command

    QMAKE_CXXFLAGS += -Xpreprocessor -fopenmp
    QMAKE_LFLAGS  +=  -Xpreprocessor -fopenmp

LIBS += -L/usr/local/lib -lcfitsio -lcurl -lfftw3_omp -lfftw3 -lm -lgsl -lgslcblas -lwcs -ltiff -lraw -lomp

from https://stackoverflow.com/questions/40095958/apple-clang-fopenmp-not-working

The -L/usr/local/lib is a local fix to get cfitsio from the brew-installed one.

2) cpu.cc and ram.cc do not compile

replace in both files

```
#ifdef __MACH__
#include <mach/mach.h>
define MACOS
#elif __LINUX__
define LINUX
#endif
```

with this
```
#ifdef __MACH__
#include <mach/mach.h>
#define MACOS
#elif __LINUX__
#define LINUX
#endif
```
I am now able to start the program itself, after installing the dependencies (some of which can be installed using brew). I do need to set THELIDIR and update PATH in Qt's Run Settings tab.

Most dependencies can either be installed using brew, or by following the instructions in INSTALL. scamp was the only external dependency that was more involved. Brew's version is too old so I build from scratch, after applying's brew's patches for using Apple's Accelerate framework to the scamp 2.7.8 source code.

For evaluating whether Theli runs properly I guess I need some data files with known results. My own data is all at the beginning amateur astrophotography level using a DSRL and a 66 mm Zenithstar telescope.

**Comment by schirmermischa** [comment]
Hi Sander, many thanks for your feedback! We got THELI working on Mojave in January, albeit only with a single CPU. Your points concerning the QMAKE flags might solve this issue, which would be great. I don't have a Mac available for testing at my home office. If you could get in touch by email at schirmer(at)mpia.de we will be able to solve this more efficiently.

**Comment by schirmermischa** [comment]
The master branch now contains the adjustments you suggested. Please let me know how it works. There is probably still an issue extracting the memory (and possibly CPU) loads shown in the two top right progress bars. It might even crash the UI. Since I don't have a mac box for testing, I'm flying blindly ...

**Comment by schirmermischa** [comment]
Compilation on Catalina is now successful.
