### ISSUE TITLE
THELI complains it cannot found astrometry.net installation

### ISSUE THREAD

**Issue by dsanmartim** [schirmermischa/THELI#4]
Hi Mischa,

I've installed THELI on Ubuntu 20.04 LTS and it seems to be working fine, but I get the following message when I run the THELI executable (the GUI opens smoothly):

"Astrometry.net installation was not found. Corresponding solvers are deactivated"

although the astrometry.net was correctly installed on "/usr/local/astrometry/" folder. Is there a way to tell THELE that it should look in this folder?

I'm aware that astrometry.net is optional, but would be great if you can help me with that.

Thanks a lot!

**Comment by kaythriemer** [comment]
Hi,
just an idea from me.
As far as I know theli scans the standard paths to find the executables.
I think "/usr/local/bin" will be part of $PATH on your system.
You can check this with "echo $PATH".
The executable for Astrometry.net is "solve-field".

If you have installed Astrometry.net in directory "/usr/local/astrometry/" it will not be found by theli. Please find "solve-field" in "/usr/local/astrometry/" or a subfolder and add this to your $PATH (e.g. "/usr/local/astrometry/bin").

Another way is to install Astrometry.net with "apt install astrometry.net". This will install it in a system path where theli will find it.


Kind regards,
Kay

**Comment by schirmermischa** [comment]
Hi David,

nice to hearing from you, hope all is fine in Chile. Kay already pointed you to the correct solution. All that is needed is that you include the path that contains the "solve-field" executable in your $PATH environment variable.

Let me know if this solves your issue.

Best,

mischa

**Comment by dsanmartim** [comment]
Hi Guys, 

Thanks a lot for replying. It's working now! As easy as running the "apt install astrometry.net" command. I just reinstalled astrometry.net using the repository package instead of building it from source. 

Very excited now to do the data reduction. Thank you both for the amazing improvement you did with THELI. I'll spread the word that it is now very easy to install :)

PS: Hope you and your family are equally well. Working from home is a bit boring, but hopefully we well be back to usual business soon.

Best,
David.
