### ISSUE TITLE
Compilation on Ubuntu 18.04

### ISSUE THREAD

**Issue by JonahDW** [schirmermischa/THELI#5]
Hello,

I'm trying to install THELI on my laptop running Ubuntu 18.04, but I'm running into a problem where somehow the WCS library is not found (or so it seems), even though it was installed along with all the other dependencies specified in the install file:
```
$ sudo apt install libwcstools-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libwcstools-dev is already the newest version (3.9.5-2).
```

However I still get the following:
```
g++ -c -pipe -fopenmp -Wall -O3 -O2 -std=gnu++11 -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/jonah/THELI/src"' -I. -isystem /usr/include/wcslib/ -isystem /usr/local/include/wcslib/ -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cc
In file included from abszp/../myimage/myimage.h:23:0,
                 from abszp/abszeropoint.h:25,
                 from mainwindow.h:26,
                 from main.cc:20:
abszp/../myimage/../tools/detectedobject.h:26:10: fatal error: wcs.h: No such file or directory
 #include "wcs.h"
          ^~~~~~~
compilation terminated.
Makefile:1659: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

Any help would be greatly appreciated. 

Cheers,
Jonah

**Comment by alexmyczko** [comment]
It get's installed into `/usr/include/wcstools/wcs.h`, so the `#include` should be `"wcstools/wcs.h"` or the `-I ` include path adapted

**Comment by kaythriemer** [comment]
Hi Jonah,

if I remember correctly I installed following packages in addition:

wcslib-dev liblapack-dev git libraw-dev

wcslib-dev will contain wcs.h


Cheers,

Kay

**Comment by JonahDW** [comment]
Thanks both for the fast responses!

Either works, but ultimately @kaythriemer 's solution is a bit more convenient because I won't have to fiddle around with the source. Though it would be useful if either the package requirements are updated or the have the #include point to the right directory.

Cheers,
Jonah

**Comment by JonahDW** [comment]
Spoke too soon it seems, a new issue has popped up with LibRaw. I've tried installing v0.19.5, but that doesn't seem to do much of anything. Still while compiling, it gives the error:

```
g++ -c -pipe -fopenmp -Wall -O3 -O2 -std=gnu++11 -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/jonah/THELI/src"' -I. -isystem /usr/include/wcslib/ -isystem /usr/local/include/wcslib/ -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o splitter_RAW.o tools/splitter_RAW.cc
tools/splitter_RAW.cc: In member function ‘void Splitter::importRAW()’:
tools/splitter_RAW.cc:70:44: error: ‘struct libraw_makernotes_t’ has no member named ‘common’; did you mean ‘canon’?
 #define P3 rawProcessor.imgdata.makernotes.common
                                            ^
tools/splitter_RAW.cc:102:18: note: in expansion of macro ‘P3’
     sensorTemp = P3.SensorTemperature;
                  ^~
tools/splitter_RAW.cc:70:44: error: ‘struct libraw_makernotes_t’ has no member named ‘common’; did you mean ‘canon’?
 #define P3 rawProcessor.imgdata.makernotes.common
                                            ^
tools/splitter_RAW.cc:103:18: note: in expansion of macro ‘P3’
     cameraTemp = P3.CameraTemperature;
                  ^~
Makefile:3841: recipe for target 'splitter_RAW.o' failed
make: *** [splitter_RAW.o] Error 1

```
Sorry to keep bothering, but I am not very well versed in chasing down C errors.

Cheers,
Jonah

**Comment by kaythriemer** [comment]
Hi Jonah,
I think this is an issue because of  a change in libraw v0.20 which is used in future Debian distribution. This change was included in theli 3.0.4 to be compatible with future versions of Debian.
My suggestion is ( as workaround, probably Mischa has an better idea) to use theli 3.0.3 (https://github.com/schirmermischa/THELI/releases/tag/v3.0.3) on Ubuntu 18.04 in the meantime.
I assume you used the master branch, correct ?
Cheers,
Kay

**Comment by JonahDW** [comment]
Hey Kay,
I was using master branch, the v3.0.3 seems to work. Thanks!
Cheers,
Jonah

**Comment by schirmermischa** [comment]
Hi Jonah,

the latest branch (3.0.4) is compatible with libraw 0.20. Is the issue with the include path for wcs.h considered resolved or does it require action on my end?

mischa

**Comment by JonahDW** [comment]
Hey Mischa,

the issue with the include path for wcs.h is that it will work either if I install wcslib-dev, or change the include path "wcstools/wcs.h", because this is where it is located for libwcstools-dev. So on my end it is resolved, but someone might run into the same issue in the future.

The simplest solution I think would be to include wsclib-dev (and maybe some of the other packages mentioned by @kaythriemer ) in the command that installs required dependencies specified in the Install file. 

Cheers,
Jonah

**Comment by schirmermischa** [comment]
The Debian package is being fixed. And the latest pushed version is backwards compatible to libraw 0.19
