### ISSUE TITLE
Installation package wcslib-dev missing; add comment about libraw

### ISSUE THREAD

**Issue by terben** [schirmermischa/THELI#6]
I just compiled THELI v3 on a fresh Ubuntu 18.04 system.

In your package list on the INSTALL page, I needed to add `wcslib-dev`. Without that, I got a missing 'wcs.h' header file error during compilation.

Perhaps you add in the comments to `libraw` that it needs to be installed from the sources. The libraw version in Ubuntu18.04 (package `libraw-dev`) is too old.

**Comment by schirmermischa** [comment]
The INSTALL file was updated accordingly.
