### ISSUE TITLE
Clarification for installation procedure

### ISSUE THREAD

**Issue by terben** [schirmermischa/THELI#7]
Hi Mischa,

Here two more small clarifications that you could add to the installation instructions:

- The `Astrometry.net` executables must be in the users PATH. Otherwise THELI reports that it is not installed. With a standard install of `Astrometry.net` this is `/usr/local/Astrometry/bin`.
- Be specific whether you need python2 or python3. I also would replace all `python` calls with an explicit `python2` or `python3` to avoid any issues. I saw `python` being an alias to `python2` or `python3` on various systems.

Cheers, Thomas

**Comment by schirmermischa** [comment]
Hi Thomas, thx for the suggestions. I have included the a.net installation path in the search path, so the binaries don't have to be included in the PATH variable anymore. Python 2 was a fall-back solution in case python 3 was not found. It should work with both. But to avoid conflicts, and given that python 2 is no longer supported, THELI now requires python 3.
