### ISSUE TITLE
MJD-OBS keyword in LBC_RED

### ISSUE THREAD

**Issue by seib2** [schirmermischa/THELI#8]
Hi,

When processing data for LBC_RED, the HUD reformating step looks for the fits header keyword 'MJD-OBS' when in fact is it 'MJD_OBS' in LBT archive data. This causes the warning:
`*.fits : Could not determine keyword: MJD-OBS, set to 58849.000000 (2020-01-01)
Some processing tasks (background modeling, proper motion correction) will not work correctly.`
and leads to a bunch of later steps failing.

Manually changing the header keyword name in all input files fixes the problem. The code should probably check for both. Potentially an issue for LBC_BLUE and others too.

**Comment by seib2** [comment]
Hi, 

The same error happens during astrometric correction, when the script looks for the 'DATE-OBS' keyword while the LBC archive keyword is 'DATE_OBS'.

**Comment by schirmermischa** [comment]
Hi, I have made the necessary adjustments, which are available now in the latest master branch. Please let me know if they are working.

**Comment by seib2** [comment]
Hi,

Just checked on a fresh install, the HUD reformatting and the astrometric solution now grab the correct keyword. Cheers!
